# Generated by Django 4.1.3 on 2022-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("default_sample_rate", models.FloatField(default=0.1)),
                ("active_sample_rate", models.FloatField(default=0.1)),
                ("active_window_end", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
