# Generated by Django 4.1.3 on 2023-01-06 12:24

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import controller.sentry.models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="wsgi_ignore_path",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=controller.sentry.models.get_default_wsgi_ignore_path,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="reference",
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
