# Generated by Django 4.1.3 on 2023-01-06 13:18

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0002_app_wsgi_ignore_path_alter_app_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("WSGI", "WSGI")], max_length=10)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("data", models.JSONField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="sentry.app",
                    ),
                ),
            ],
        ),
    ]
