# Generated by Django 4.1.5 on 2023-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0003_app_celery_ignore_task_app_celery_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="celery_collect_metrics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="app",
            name="wsgi_collect_metrics",
            field=models.BooleanField(default=False),
        ),
    ]
