# Generated by Django 4.1.3 on 2023-01-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0003_metric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metric",
            old_name="timestamp",
            new_name="last_updated",
        ),
    ]
