# Generated by Django 4.1.5 on 2023-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0004_app_celery_collect_metrics_app_wsgi_collect_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="celery_metrics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="app",
            name="wsgi_metrics",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
