# Generated by Django 4.1.3 on 2023-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0004_rename_timestamp_metric_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
