# Generated by Django 4.1.5 on 2023-01-12 12:39
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "__latest__"),
        ("auth", "__latest__"),
        ("admin", "__latest__"),
        ("sessions", "__latest__"),
        ("sentry", "0005_alter_app_celery_metrics_alter_app_wsgi_metrics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "permissions": [
                    ("bump_sample_rate_app", "Can bump sample rate"),
                    ("panic_app", "Panic! Set all sample rate to 0"),
                ]
            },
        ),
    ]
