# Generated by Django 4.1.3 on 2023-01-06 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0005_alter_metric_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="last_updated",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
