# Generated by Django 4.1.5 on 2023-01-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0006_alter_app_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "permissions": [
                    ("bump_sample_rate_app", "Can bump sample rate"),
                    ("panic_app", "Panic! Set all sample rate to 0"),
                ]
            },
        ),
    ]
