# Generated by Django 4.1.5 on 2023-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0006_alter_app_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="sentry_project_slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
