# Generated by Django 4.1.5 on 2023-01-09 08:13

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import controller.sentry.models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0006_alter_metric_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="celery_ignore_task",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=controller.sentry.models.get_default_celery_ignore_task,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="type",
            field=models.CharField(
                choices=[("WSGI", "WSGI"), ("CELERY", "CELERY")], max_length=10
            ),
        ),
    ]
