# Generated by Django 4.1.6 on 2023-02-03 14:36

from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def apply_migration(apps, schema_editor):
    emit_post_migrate_signal(2, False, "default")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    owner = Group.objects.get(name="Owner")
    admin = Group.objects.get(name="Admin")
    developer = Group.objects.get(name="Developer")

    metric_permission = Permission.objects.get(codename="enable_disable_metrics_app")

    owner.permissions.add(metric_permission)
    admin.permissions.add(metric_permission)
    developer.permissions.add(metric_permission)


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0007_app_sentry_project_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "permissions": [
                    ("bump_sample_rate_app", "Can bump sample rate"),
                    ("panic_app", "Panic! Set all sample rate to 0"),
                    ("enable_disable_metrics_app", "Can Enable/Disable metrics"),
                ]
            },
        ),
        migrations.RunPython(apply_migration, migrations.RunPython.noop),
    ]
