# Generated by Django 4.1.6 on 2023-02-07 14:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0008_alter_app_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("sentry_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("sentry_project_slug", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="app",
            name="sentry_project_slug",
        ),
        migrations.AddField(
            model_name="app",
            name="command",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="env",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("reference", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("SUCCESS", "success"), ("FIRING", "firing"), ("DISCARD", "discard")],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="sentry.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="app",
            name="sentry_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apps",
                to="sentry.project",
            ),
        ),
    ]
