# Generated by Django 4.1.6 on 2023-02-07 15:08

import functools

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import controller.sentry.models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0009_project_remove_app_sentry_project_slug_app_command_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="detection_param",
            field=models.JSONField(
                default=functools.partial(
                    controller.sentry.models.settings_default_value, *("DEFAULT_SPIKE_DETECTION_PARAM",), **{}
                )
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="celery_ignore_task",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=functools.partial(
                    controller.sentry.models.settings_default_value, *("DEFAULT_CELERY_IGNORE_TASKS",), **{}
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="wsgi_ignore_path",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=functools.partial(
                    controller.sentry.models.settings_default_value, *("DEFAULT_WSGI_IGNORE_PATHS",), **{}
                ),
                size=None,
            ),
        ),
    ]
