# Generated by Django 4.1.6 on 2023-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0010_project_detection_param_alter_app_celery_ignore_task_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RenameField(
            model_name="app",
            old_name="sentry_project",
            new_name="project",
        ),
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(choices=[("FIRING", "firing"), ("DISCARD", "discard")], max_length=10),
        ),
    ]
