# Generated by Django 4.1.6 on 2023-02-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0012_project_detection_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sentry.event",
            ),
        ),
    ]
