# Generated by Django 4.1.6 on 2023-02-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0013_project_last_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="celery_collect_metrics",
            field=models.BooleanField(default=False, verbose_name="celery metrics"),
        ),
        migrations.AlterField(
            model_name="app",
            name="wsgi_collect_metrics",
            field=models.BooleanField(default=False, verbose_name="wsgi metrics"),
        ),
    ]
