# Generated by Django 4.2 on 2023-05-28 14:20

import functools

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import controller.sentry.models


class Migration(migrations.Migration):
    dependencies = [
        ("sentry", "0014_alter_app_celery_collect_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="wsgi_ignore_user_agent",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=functools.partial(
                    controller.sentry.models.settings_default_value, *("DEFAULT_WSGI_IGNORE_USER_AGENT",), **{}
                ),
                help_text="A list of user agent to ignore, matched with startswith",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="wsgi_ignore_path",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=functools.partial(
                    controller.sentry.models.settings_default_value, *("DEFAULT_WSGI_IGNORE_PATHS",), **{}
                ),
                help_text="A list of path to ignore, matched using fill match ==",
                size=None,
            ),
        ),
    ]
