
global:
  scrape_interval: 15s
  evaluation_interval: 20s

scrape_configs:
  - job_name: "sentry_controller_metrics"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["statsd-exporter:9102"]
        labels:
          app: 'sentry_controller'
